### ISSUE TITLE
Support for batch / build-matrix?

### ISSUE THREAD

**Issue by irbrad** [aws-actions/aws-codebuild-run-build#107]
I'm running into an issue where I'm trying to set environment variables inside of the buildspec.yml but the variables are never set during install/build steps of the CodeBuild process.  The buildspec.yml has the following in it:

```
batch:
  build-matrix:
    dynamic:
      env:
        variables:
          <<snip>>
```

Is this something that isn't supported?
