### ISSUE TITLE
Image override does not work

### ISSUE THREAD

**Issue by sphennings** [aws-actions/aws-codebuild-run-build#108]
When I attempt to use the image override option, codebuild still uses the default container and I get a warning in the logs. 

`Warning: Unexpected input(s) 'image-override', valid inputs are ['project-name', 'buildspec-override', 'env-vars-for-codebuild']`

```yaml
- name: Codebuild
   uses: aws-actions/aws-codebuild-run-build@v1
   with:
     project-name: project_name
     image-override: overide_image_uri
```
