### ISSUE TITLE
Logs are missing when CodeBuild uses Compute fleets

### ISSUE THREAD

**Issue by mic-kul** [aws-actions/aws-codebuild-run-build#171]
Hi,

We're encountering an issue with the `aws-codebuild-run-build` action when using CodeBuild Compute fleets: the logs are missing, whenever generating output takes more than 60s (default updateInterval 30s).

I've checked CloudWatch GetLogEvents metrics and found no errors.

We run this with default update interval of 30 seconds.

First, I thought we were encountering the condition described in [this section of the code](https://github.com/aws-actions/aws-codebuild-run-build/blob/main/dist/index.js#L151-L153):

```
  // GetLogEvents can return partial/empty responses even when there is data.
  // We wait for two consecutive empty log responses to minimize false positive on EOF.
  // Empty response counter starts after any logs have been received, or when the build completes.
```

However, it doesn't make sense that everything works as expected when running on On Demand builders, and the issue occurs only when we run the build on CodeBuild Compute Fleet.

The minimal buildspec to reproduce the issue:

```yml
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Preparing to execute the sleep script"
  build:
    commands:
      - echo "Starting the sleep script"
      - |
        #!/bin/bash

        # Initialize total sleep time
        total_sleep_time=20

        # Loop until total sleep time reaches or exceeds 60 seconds
        while [ $total_sleep_time -lt 160 ]; do
          echo $total_sleep_time
          sleep $total_sleep_time
          total_sleep_time=$((total_sleep_time + 15))
          
        done

        echo "Total sleep time: $total_sleep_time seconds"
  post_build:
    commands:
      - echo "Sleep script execution completed"
```

Example:

When running CodeBuild On Demand started by this Github Action, GHA outputs:

<img width="1082" alt="on_demand_finished" src="https://github.com/user-attachments/assets/02d0c1a1-e0f3-43bc-b27b-bf389b4642f9">
﻿
 
When running CodeBuild Compute fleets started by this Github Action, CB&GHA output:
- in progress:
<img width="1418" alt="reservered_capacity_in_progress" src="https://github.com/user-attachments/assets/a653ebe4-ca40-4380-8a18-dd7b603c6423">

- finished:
<img width="1545" alt="reservered_capacity_finished" src="https://github.com/user-attachments/assets/61fc7ede-6e98-40c0-bed6-4a276c473d2e">

Is there anything that can be done to try to pull all missing logs again, once "CODEBUILD COMPLETE" signal is received?
