### ISSUE TITLE
how to override "source version" in github actions?

### ISSUE THREAD

**Issue by vitek-urbanec** [aws-actions/aws-codebuild-run-build#61]
Hello,

What I'd like to have is a workflow in github actions that triggers for every branch on push (defined in a workflow in `master` default branch).

This workflow should trigger `aws-codebuild-run-build` action & the codebuild project should download source from a branch `some_branch`.

If I understood correctly, `aws-codebuild-run-build` overrides the source version to the triggering commit, regardless of the settings in the codebuild project.

How do I make sure that codebuild is going to get source from the specified branch `some_branch`?

Thanks!

**Comment by jayheehee** [comment]
Hey there, were you able to find a solution? I am running into the same issue.

**Comment by solarmosaic-kflorence** [comment]
This action should support all of the source version syntax as specified by https://docs.aws.amazon.com/codebuild/latest/userguide/sample-source-version.html

**Comment by kimmoahokas** [comment]
Seems that PR https://github.com/aws-actions/aws-codebuild-run-build/pull/62 tries to address this.

**Comment by akazakou** [comment]
Probably you can use [dark-mechanicum/aws-codebuild@v1](https://github.com/marketplace/actions/dark-mechanicum-aws-codebuild) action to implement what you need.

```yaml
name: Running example
on: [push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    name: 'Deployment'
    runs-on: ubuntu-latest
    steps:
      - name: Executing AWS CodeBuild task
        uses: dark-mechanicum/aws-codebuild@v1
        env:
          CODEBUILD__sourceVersion: "my-cool-branch-name"
        with:
          projectName: '<your-aws-codebuild-job-name-here>'
```
