### ISSUE TITLE
Support `--image-override`

### ISSUE THREAD

**Issue by yellowmamba** [aws-actions/aws-codebuild-run-build#86]
Could you add support for `--image-override` option? Happy to PR myself.

**Comment by ronakfof** [comment]
https://github.com/aws-actions/aws-codebuild-run-build/pull/100

**Comment by akazakou** [comment]
Probably you can use [dark-mechanicum/aws-codebuild@v1](https://github.com/marketplace/actions/dark-mechanicum-aws-codebuild) action to implement what you need.

```yaml
name: Running example
on: [push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    name: 'Deployment'
    runs-on: ubuntu-latest
    steps:
      - name: Executing AWS CodeBuild task
        uses: dark-mechanicum/aws-codebuild@v1
        env:
          CODEBUILD__imageOverride: "The name of an image for this build that overrides the one specified in the build project"
        with:
          projectName: '<your-aws-codebuild-job-name-here>'
```
