### ISSUE TITLE
[Feature Request] Support for computeTypeOverride

### ISSUE THREAD

**Issue by eogden93** [aws-actions/aws-codebuild-run-build#95]
At current I've not seen a way to set an override for the compute type for this action.
I would like the ability to set this value as it seems to be supported by the API.
https://docs.aws.amazon.com/codebuild/latest/APIReference/API_StartBuild.html#CodeBuild-StartBuild-request-computeTypeOverride

**Comment by akazakou** [comment]
Probably you can use [dark-mechanicum/aws-codebuild@v1](https://github.com/marketplace/actions/dark-mechanicum-aws-codebuild) action to implement what you need.

```yaml
name: Running example
on: [push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    name: 'Deployment'
    runs-on: ubuntu-latest
    steps:
      - name: Executing AWS CodeBuild task
        uses: dark-mechanicum/aws-codebuild@v1
        env:
          CODEBUILD__computeTypeOverride: BUILD_GENERAL1_MEDIUM
        with:
          projectName: '<your-aws-codebuild-job-name-here>'
```
